FROM debezium/connect:2.5

USER root

# Instalação MANUAL das bibliotecas Confluent Avro e suas dependências ocultas
RUN mkdir -p /kafka/connect/kafka-connect-avro-converter && \
    cd /kafka/connect/kafka-connect-avro-converter && \
    # 1. O Conversor Principal
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/7.6.0/kafka-connect-avro-converter-7.6.0.jar && \
    # 2. Manipulação de Dados Avro
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-data/7.6.0/kafka-connect-avro-data-7.6.0.jar && \
    # 3. Serializadores
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/7.6.0/kafka-avro-serializer-7.6.0.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.6.0/kafka-schema-serializer-7.6.0.jar && \
    # 4. Cliente do Registry
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.6.0/kafka-schema-registry-client-7.6.0.jar && \
    # 5. Configurações Comuns
    curl -sO https://packages.confluent.io/maven/io/confluent/common-config/7.6.0/common-config-7.6.0.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/common-utils/7.6.0/common-utils-7.6.0.jar && \
    # 6. A PEÇA QUE FALTAVA (AbstractDataConfig mora aqui agora)
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-schema-converter/7.6.0/kafka-schema-converter-7.6.0.jar && \
    # 7. Dependências Externas (Apache Avro & Google Guava)
    curl -sO https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.3/avro-1.11.3.jar && \
    curl -sO https://repo1.maven.org/maven2/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar && \
    curl -sO https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar

USER kafka