CREATE SCHEMA IF NOT EXISTS access;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS sys;
CREATE SCHEMA IF NOT EXISTS utils;

CREATE EXTENSION IF NOT EXISTS pgcrypto;